# NOTE: this likely can be refined! I was in "get it working!" mode!
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: state-machine-cluster-roles
rules:
- apiGroups:
  - ""
  - batch
  resources: ["pods", "miniclusters", "customresourcedefinitions", "jobs", "configmaps", "jobs/status"]
  verbs: ["list", "get", "patch", "create", "delete", "watch"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: state-machine-roles
rules:
- apiGroups:
  - ""
  - batch
  resources: ["pods", "miniclusters", "customresourcedefinitions", "jobs", "jobs/status", "configmaps"]
  verbs: ["list", "get", "patch", "create", "delete", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: state-machine-roles
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: state-machine-cluster-roles
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: state-machine-roles
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: state-machine-roles
  apiGroup: rbac.authorization.k8s.io
