apiVersion: state-machine.converged-computing.org/v1alpha1
kind: StateMachine
metadata:
  name: state-machine
spec:
  manager:
    pullPolicy: Never
  workflow:
    completed: 4
  cluster:
    maxSize: 6

  jobs:
  - name: job_a
    registry:
      push: job_a
    config:
      nodes: 1
      coresPerTask: 1
    image: rockylinux:9
    script: |
      # This will start in the config->workdir, and pull/push according to the config
      sleep 20
      echo "${jobid}" > ${jobid}-a.txt

  - name: job_b
    config:
      nodes: 1
      coresPerTask: 1
    image: rockylinux:9
    registry:
      pull: job_a
      push: job_b
    script: |
      sleep 20
      touch ${jobid}-b.txt

  - name: job_c
    config:
      nodes: 1
      coresPerTask: 1
    image: rockylinux:9
    registry:
      pull: job_b
      push: job_c
    script: |
      sleep 20
      touch ${jobid}-c.txt
