apiVersion: state-machine.converged-computing.org/v1alpha1
kind: StateMachine
metadata:
  name: workflow-sample
spec:
  workflow:
    completed: 4
  cluster:
    maxSize: 6
  jobs:
  - name: job_a
    config:
      nodes: 1
      nproc: 1
      coresPerTask: 6
    image: rockylinux:9
    script: |
      jobid={{ jobid }}

      outpath=/tmp/out
      registry="{{ registry }}"

      echo ">> jobid        = $jobid"
      echo ">> outpath      = $outpath"
      echo ">> registry     = $registry"
      echo ">> hostname     = "$(hostname)

      mkdir -p -v $outpath; cd $outpath

      # This gets pushed to the registry with the tag corresponding to the step
      sleep 20
      echo "${jobid}" > ${jobid}-a.txt
      echo "Step was successful, pushing result to $registry/${jobid}:job_a"
      oras push --plain-http --insecure $registry/${jobid}:job_a ${jobid}-a.txt

  - name: job_b
    config:
      nodes: 1
      nproc: 1
      coresPerTask: 6
    image: rockylinux:9
    script: |
      jobid={{ jobid }}

      outpath=/tmp/out
      registry="{{ registry }}"

      echo ">> jobid        = $jobid"
      echo ">> outpath      = $outpath"
      echo ">> registry     = $registry"
      echo ">> hostname     = "$(hostname)

      mkdir -p -v $outpath; cd $outpath

      echo "Looking for $jobid with oras repo list"
      oras repo list $registry --plain-http | grep ${jobid}
      echo "Pulling oras artifact to $locpath"
      oras pull $registry/${jobid}:job_a --plain-http

      sleep 20
      touch ${jobid}-b.txt
      ls
      retval=$?
      if [ $retval -eq 0 ];
        then
          echo "Pushing results to $registry/${jobid}:job_b"
          oras push --plain-http --insecure $registry/$jobid:job_b .
      fi

  - name: job_c
    config:
      nodes: 1
      nproc: 1
      coresPerTask: 6
    image: rockylinux:9
    script: |
      jobid={{ jobid }}

      outpath=/tmp/out
      registry="{{ registry }}"

      echo ">> jobid        = $jobid"
      echo ">> outpath      = $outpath"
      echo ">> registry     = $registry"
      echo ">> hostname     = "$(hostname)

      mkdir -p -v $outpath; cd $outpath

      echo "Looking for $jobid with oras repo list"
      oras repo list $registry --plain-http | grep ${jobid}
      echo "Pulling oras artifact to $locpath"
      oras pull $registry/${jobid}:job_b --plain-http

      sleep 20
      touch ${jobid}-c.txt
      ls
      retval=$?
      if [ $retval -eq 0 ];
        then
          echo "Pushing results to $registry/${jobid}:job_c"
          oras push --plain-http --insecure $registry/$jobid:job_c .
      fi
